api_platform:
  oauth:
    # To enable or disable OAuth.
    enabled: true

    # The OAuth client ID.
    clientId: 'eea4729dfd87507e52f4b1d1c0a27817'

    # The OAuth client secret.
    clientSecret: '451d72b1b9b232b99da807d077d5088a31e27c41c9b3e7fdc14c14745e2b13b06941f05789009f1ceb5ac5e08493c7bf2bd2cde33679f5cd1ea810ada115d6a7'

    # The OAuth type.
    type: 'oauth2'

    # The OAuth flow grant type.
    flow: 'password'

    # The OAuth token url.
    tokenUrl: '/token'

    # The OAuth authentication url.
    authorizationUrl: '/oauth/v2/auth'

    # The OAuth scopes.
    scopes: []