# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    App\Controller\LogoutController:
<<<<<<< HEAD
        arguments:
            $tokenStorage: '@security.token_storage'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: [ 'controller.service_arguments' ]
        public: true
=======
        public: true # установите опцию "public" в true
        tags: ['controller.service_arguments']
        arguments:
            - '@security.csrf.token_manager'

>>>>>>> 19a5e1714805b4f25cbe970f799bd7b11afc7ed2
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
