<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJFjPbtg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJFjPbtg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJFjPbtg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJFjPbtg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJFjPbtg\App_KernelDevDebugContainer([
    'container.build_hash' => 'JFjPbtg',
    'container.build_id' => 'ac485ae7',
    'container.build_time' => 1679137971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJFjPbtg');
